### ISSUE TITLE
Doesn't work on some people

### ISSUE THREAD

**Issue by sepgh** [iamvee/how-to-start-a-conversation-with-a-developer#1]
I have used the provided methods on some people who called themselves developers. Didn't work! I have tried to fix this issue but nothing has worked so far!

I think the bug has appeared in this commit: [4d69a69af59ea14abb66e81886d9337bd8d97ddd](https://github.com/iamvee/how-to-start-a-conversation-with-a-developer/commit/4d69a69af59ea14abb66e81886d9337bd8d97ddd)

**Comment by iamvee** [comment]
Thanks @sepehr-gh I'm going to fix this bug and add a few more topics to the list as soon as possible (next stable release 0.0.1) 

cheers

**Comment by EleRam** [comment]
@sepehr-gh Please explain the steps or share the debug logs to reproduce. also, consider telling us some details about your case.

**Comment by sepgh** [comment]
@EleRam Well there are different cases that I could not get things working as expected! Like yesterday I went to a bar and I saw a girl wearing a T-Shirt with `I love python` on it. I thought nice, she might be the one, so I went to her and asked:  `space or tab?`, and she just walked away!

**Comment by iamvee** [comment]
Guess, those artifacts @sepehr-gh reported does not necessarily apply to the remaining cases. There's a hasty generalization though! You simply ignore the `environment variables`, say, the widespread impact of covid-19; well it's been expected stay at home and avoid any kinda human interaction, not going ahead and start to flirt. 

please consider, during the lockdown, all of those topics MUST NOT performed in person.

**Comment by sepgh** [comment]
Oh right. I will re-check my `environment variables` and retry later. I will post the descriptions in a new issue if the bug appeared again. I also found out you have updated this repository. perhaps the new version works just fine. Closing this. thanks.

btw: all of these are impacts of Covid-19 :))))
