### ISSUE TITLE
tab or space doesn't show well

### ISSUE THREAD

**Issue by rsharifnasab** [iamvee/how-to-start-a-conversation-with-a-developer#3]
hi, in tab or space section, you put entire conversation in `this style` and put tab and space words again in `same style`, this isn't work well, do you have any idea to fix it?
![image](https://user-images.githubusercontent.com/11211946/77891830-d2709880-7286-11ea-8341-6dd19c55d281.png)

**Comment by iamvee** [comment]
well, I fixed this one by replacing the character. and please let me know if there's any problem with implementing this repository on Docker. 

cheers
